class string:
    enterFileName: str = "enter file name :"
    enterContent: str = "enter content :"
    enterTask: str = "enter the task :"
    enterData: str = "enter your data :"
    enterLengthForString: str = "enter length for string :"
    suggestion: str = "suggested type (str, int, float)"
    qus1: str = "what process you want?"
    enterPublicKey: str = "enter your publicKey :"
    welcome: str = "Welcome to the mystical castle"
    thankYou: str = "thank you!"
    initialFileContent: str = "//Hello, world!\n//This is a new file created using Python."
    folderCreatedSuccessfully: str = "Folder created successfully."
    failToCreate: str ="Failed to create folder."